### ISSUE TITLE
create_media is "slow"

### ISSUE THREAD

**Issue by sergii-bond** [Cogniac/cogniac-sdk-py#11]
This is what I experience when running this snapshot of code that includes [create_media](https://github.com/Cogniac/cogniac-sdk-py/blob/f6f1fbc31b2cf97edbb30d6b19024705af308e97/cogniac/cogniac.py#L211).

```
447                     t0 = time()
448                     m = cc.create_media(impath_out, meta_tags=[ttfile, str(txt_size), txt])
449                     t1 = time()
450                     ocr_subject.associate_media(m, app_data_type='ocr', app_data=txt)
451                     t2 = time()
452                     print("CM t: {0:.0f} ms, AM t: {1:.0f} ms, FSIZE: {2} bytes".format(
453                         1000 * (t1 - t0),
454                         1000 * (t2 - t1),
455                         os.path.getsize(impath_out)))
```

Several seconds of running this code is output here:
[log2.txt](https://github.com/Cogniac/cogniac-sdk-py/files/1174675/log2.txt)

The file size is quite small, though it takes more than 100ms to upload it, sometimes several times longer than that.

In another instance, it took me two or three days to upload only 700k images.
I understand I can use multiprocessing for this task, but I thought to point out first that a single process seems to take long time. After all, when using multiprocessing, the speed limit will be hit at some point when it can't scale on a single machine. Which seems to be true when I attempt running 16 processes on gpuws0.

**Comment by wskish** [comment]
Closing this now that we have added a 'cogupload' script as a reference to how to parallelize the upload process to be able to consume pretty much all available upload access bandwidth.
