### ISSUE TITLE
Getting the whole application details is not possible

### ISSUE THREAD

**Issue by pmranade** [Cogniac/cogniac-sdk-py#16]
If I know the app_id and I want to get all the details of this app (like per subject detection threshold etc) I couldn't find it.
I tried 
cc = cogniac.CogniacConnection(tenant_id=TENANT_ID, timeout=TIMEOUT)
app = cogniac.CogniacApplication.get(cc, app_id)
But this just returns the name and app_id, no other details.

**Comment by wskish** [comment]
use cc.get_application() to get the application
