### ISSUE TITLE
create media times out while public-api/media-service is processing media

### ISSUE THREAD

**Issue by pmranade** [Cogniac/cogniac-sdk-py#18]
The default timeout for the connection is set to 20sec
This is smaller than the timeout enforced by by ELB or nginx (60 sec by default)
It is good to keep this short as this is session timeout for all calls but we might want to increase this at least for the post media calls as those operations can take longer than 20 sec

**Comment by pmranade** [comment]
I tried changing all the timeouts in media.py to be 20 times the timeout in cogniac.py (just to make it large, we can figure out what this no should really be or fix the timeou at 60 sec for media calls)
I tried uploading 900+Mb file 5 times and was able to upload successfully.
When I removed the timeout multiplier from media.py and tried multiple times, I got the timeout error everytime

**Comment by wskish** [comment]
closing as the default timeout is 60s now.  https://github.com/Cogniac/cogniac-sdk-py/blob/60cb735a5f7f7346bf5ff94c03cceef7d8091392/cogniac/cogniac.py#L76
