### ISSUE TITLE
SDK needs to set a default encoding when the sys.stdout.encoding is not set

### ISSUE THREAD

**Issue by deepshikha-jha** [Cogniac/cogniac-sdk-py#37]
CogniacConnection that does nothing more than print the result of CogniacConnection.get_all_subjects().
This method works fine if I print to stdout, but if I redirect the output to a file (using Unix redirection) I get the following error:

    print cc.get_all_subjects()
  File "/Users/i012387/anaconda3/envs/cogniac/lib/python2.7/site-packages/cogniac/subject.py", line 216, in __repr__
    return s.encode(sys.stdout.encoding)
TypeError: encode() argument 1 must be string, not None

It makes total sense to assume that the encoding exists, but that isn't necessarily true. Try this out: create a file called test.py and add these lines:
import sys
print(sys.stdout.encoding)

Now compare
$ python test.py
UTF-8
$ python test.py > out; cat out
None

**Comment by deepshikha-jha** [comment]
We might need to set a default encoding here
```def __str__(self):
        s = "%s (%s)" % (self.name, self.subject_uid)
        return s.encode(sys.stdout.encoding)```

**Comment by wskish** [comment]
closing this as it is not clear if it is our responsibility to set this versus the sdk user
