### ISSUE TITLE
Create media from buffer, skipping disk write

### ISSUE THREAD

**Issue by sergii-bond** [Cogniac/cogniac-sdk-py#39]
I can download media to a buffer through sdk without saving it to disk. I'd like to create media in the similar way, from a buffer. This will save many disk operations and its tear and wear. 

It could also accept a file object, and a user would use `f = io.BytesIO(buf)` or similar to prepare it.

**Comment by wskish** [comment]
implemented via https://github.com/Cogniac/cogniac-sdk-py/commit/5aa5fe0114ea3dbb59a693f020f8b6b7e7025d83
