### ISSUE TITLE
increased download robustness with range headers

### ISSUE THREAD

**Issue by wskish** [Cogniac/cogniac-sdk-py#50]
Download of media, models, and (upcoming) EdgeFlow software images should be made more resilient to transient network failures by the use of [HTTP range headers](https://tools.ietf.org/html/rfc7233).   

When downloading these large media/model/image files:

Upon requests completion, check that the total number of bytes downloaded equals the size specified in the Content-Length HTTP header.

If the total cumulative number of bytes downloaded does not equal the Content-Length, continue the download with a range header that looks something like

Range: bytes=4567890-

which requests should accept as a header dict with 'Range' key and corresponding text string.

If writing to a file take care to fseek(fp, 0, SEEK_END) prior to subsequent range downloads.

**Comment by mgub** [comment]
@wskish Do you want software download calls exposed in the SDK?

**Comment by wskish** [comment]
I dont think it is necessary to support ef software download from sdk.   Still think the range header support is a good idea but perhaps it doesn't belong in the sdk.

**Comment by wskish** [comment]
closing this as major use cases have been addressed elsewhere
