### ISSUE TITLE
Add configurable FQDN to EdgeFlow

### ISSUE THREAD

**Issue by mgub** [Cogniac/cogniac-sdk-py#57]
In https://github.com/Cogniac/cogniac-sdk-py/pull/51 it was hard-coded to api.cogniac.io. It should set the FQDN for CloudCore API calls with `os.environ.get("COG_URL_PREFIX", "api.cogniac.io")`.

**Comment by amycogniac** [comment]
and can we not requiring gateway url prefix for the functions that we don't need it?

**Comment by wskish** [comment]
yeah the CogniacConnection already knows how to prepend the correct url prefix (see e.g. https://github.com/Cogniac/cogniac-sdk-py/blob/d3a04d409505fda7f084b300ceba25cca3a836c3/cogniac/cogniac.py#L206) so we don't need to specify it elsewhere.

**Comment by mgub** [comment]
Seems stale. Closing for now.
