### ISSUE TITLE
change in app.app_type_config is not saved automatically

### ISSUE THREAD

**Issue by ymtsang** [Cogniac/cogniac-sdk-py#73]
In cogniac application object, if there is a change in an attribute value, the attribute value should be saved automatically, as specified in line:
https://github.com/Cogniac/cogniac-sdk-py/blob/764f360cfeac301bc3583fab397b40a4f3586e50/cogniac/app.py#L145

However, app_type_config is a dictionary. Changing a key-value insides the app_type_config dict does not change the id (or pointer) to app_type_config dict. Hence, the above set_attr is not triggered.

To reproduce,
```python
app_id = "some app_id"
app = cc.get_application(app_id)
app.app_type_config['fps_requirement'] = 2
app = cc.get_application(app_id)
```  
You will see the change is not saved. However if you do the following, the change is saved:
```python
import copy
app_id = "some app_id"
app = cc.get_application(app_id)
app.app_type_config['fps_requirement'] = 2
app.app_type_config = copy.deepcopy(app.app_type_config)
app = cc.get_application(app_id)
```

**Comment by wskish** [comment]
Preferred solution is to make the individual composite items (e.g. app_type_config) first class objects of their own which react appropriately with their own __settattr__
