### ISSUE TITLE
"update" function of CogniacNetworkCamera doesn't seem to update the python object.

### ISSUE THREAD

**Issue by sergii-bond** [Cogniac/cogniac-sdk-py#78]
[here](https://github.com/Cogniac/cogniac-sdk-py/blob/1b05e26c83b4b40b43d5ef9ea081cf4d46fde660/cogniac/network_camera.py#L162) is this function. It returns a new CogniacNetworkCamera object. I saw users of sdk using this function as:

```netcam.update(...)```

and likely expecting netcam object itself to have updated parameters. The correct call would be 
```netcam = netcam.update(...)```, but that doesn't look intuitive to do.

**Comment by sergii-bond** [comment]
Test case:

``` python
import cogniac
from cogniac.network_camera import CogniacNetworkCamera

cc = cogniac.CogniacConnection(tenant_id="your_tenant")

cam_name = "test_cam"

for c in cc.get_all_cameras():
    if c.camera_name == cam_name:
        cam = c 
        print("Found a test camera")
        break
else:
    print("Creating a test camera")
    cam = CogniacNetworkCamera.create(cc, name=cam_name, url=u'gigv://169.254.23.111/')

cur_ip = cam.current_IP
print("current_IP={}".format(cur_ip))
new_ip = "10.10.0.8"
print("Attempting to update current_IP to {}".format(new_ip))
cam.update(current_IP=new_ip)
print("The updated python object has current_IP={}".format(cam.current_IP))
```

Output:
```
Found a test camera
current_IP=10.10.0.2
Attempting to update current_IP to 10.10.0.8
The updated python object has current_IP=10.10.0.2
```

**Comment by wskish** [comment]
the broader issue here is the update function is a bit off-idiom for the sdk.  the netcam interface should be updated to support setattr-style updates for consistence with the other first class objects.

**Comment by sergii-bond** [comment]
setattr function already exists for camera objects. Should we just ensure `camera_model_keys` at the top of the network_camera.py file includes all attributes that `update` function has, and remove the `update` function ?

**Comment by wskish** [comment]
yes; please add a deprecation warning to the update function and we can plan to remove it in a subsequent version
